ValueError
Python 3.9.7: E:\Anaconda3\envs\imgproapp\python.exe
Fri Dec 10 16:42:04 2021

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 E:\BaiduNetdiskWorkspace\Cloud_PythonProgramming\img-proc-app\gui\subgui_edit.py in filter(self=<gui.subgui_edit.Ui_SubWindow object>)
  815             self.horizontalSlider.valueChanged.connect(
  816                 lambda: self.defog(w_dict[self.horizontalSlider.value()]))
  817             self.defog()
  818 
  819         elif self.pushButton_3.isChecked():
self = <gui.subgui_edit.Ui_SubWindow object>
self.defog = <bound method Ui_SubWindow.defog of <gui.subgui_edit.Ui_SubWindow object>>

 E:\BaiduNetdiskWorkspace\Cloud_PythonProgramming\img-proc-app\gui\subgui_edit.py in defog(self=<gui.subgui_edit.Ui_SubWindow object>, w=0.95)
  869         '''
  870         imTemp = self.graphicsView.CVtemp.img
  871         imDst = defogging(m=imTemp / 255.0, w=w) * 255
  872         self.graphicsView.CVdst.img = imDst.astype(uint8)
  873 
imDst undefined
global defogging = <function defogging>
m undefined
imTemp = array([[[195, 194, 196],
        [192, 191, 193]...37, 135],
        [133, 138, 136]]], dtype=uint8)
w = 0.95

 E:\BaiduNetdiskWorkspace\Cloud_PythonProgramming\img-proc-app\plugins\defogger.py in defogging(m=array([[[0.76470588, 0.76078431, 0.76862745],
  ...,
        [0.52156863, 0.54117647, 0.53333333]]]), r=81, eps=0.001, w=0.95, maxV1=0.8, bGamma=True)
   58 def defogging(m, r=81, eps=0.001, w=0.95, maxV1=0.80, bGamma=True):
   59     Y = zeros(m.shape)
   60     V1, A = getV1(m, r, eps, w, maxV1)  # 得到遮罩图像和大气光照
   61     for k in range(3):
   62         Y[:, :, k] = (m[:, :, k] - V1) / (1 - V1 / A)  # 颜色校正
V1 undefined
A undefined
global getV1 = <function getV1>
m = array([[[0.76470588, 0.76078431, 0.76862745],
  ...,
        [0.52156863, 0.54117647, 0.53333333]]])
r = 81
eps = 0.001
w = 0.95
maxV1 = 0.8

 E:\BaiduNetdiskWorkspace\Cloud_PythonProgramming\img-proc-app\plugins\defogger.py in getV1(m=array([[[0.76470588, 0.76078431, 0.76862745],
  ...,
        [0.52156863, 0.54117647, 0.53333333]]]), r=81, eps=0.001, w=0.95, maxV1=0.8)
   41 def getV1(m, r, eps, w, maxV1):  # 输入rgb图像，值范围[0,1]
   42     '''计算大气遮罩图像V1和光照值A, V1 = 1-t/A'''
   43     V1 = min(m, 2)  # 得到暗通道图像
   44     V1 = guidedfilter(V1, MinFilterGray(V1, 7), r, eps)  # 使用引导滤波优化
   45     bins = 2000
V1 undefined
builtinmin = <built-in function min>
m = array([[[0.76470588, 0.76078431, 0.76862745],
  ...,
        [0.52156863, 0.54117647, 0.53333333]]])
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
    __cause__ = None
    __class__ = <class 'ValueError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of ValueError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of ValueError object>
    __doc__ = 'Inappropriate argument value (of correct type).'
    __eq__ = <method-wrapper '__eq__' of ValueError object>
    __format__ = <built-in method __format__ of ValueError object>
    __ge__ = <method-wrapper '__ge__' of ValueError object>
    __getattribute__ = <method-wrapper '__getattribute__' of ValueError object>
    __gt__ = <method-wrapper '__gt__' of ValueError object>
    __hash__ = <method-wrapper '__hash__' of ValueError object>
    __init__ = <method-wrapper '__init__' of ValueError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of ValueError object>
    __lt__ = <method-wrapper '__lt__' of ValueError object>
    __ne__ = <method-wrapper '__ne__' of ValueError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of ValueError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of ValueError object>
    __repr__ = <method-wrapper '__repr__' of ValueError object>
    __setattr__ = <method-wrapper '__setattr__' of ValueError object>
    __setstate__ = <built-in method __setstate__ of ValueError object>
    __sizeof__ = <built-in method __sizeof__ of ValueError object>
    __str__ = <method-wrapper '__str__' of ValueError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ('The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()',)
    with_traceback = <built-in method with_traceback of ValueError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "E:\BaiduNetdiskWorkspace\Cloud_PythonProgramming\img-proc-app\gui\subgui_edit.py", line 817, in filter
    self.defog()
  File "E:\BaiduNetdiskWorkspace\Cloud_PythonProgramming\img-proc-app\gui\subgui_edit.py", line 871, in defog
    imDst = defogging(m=imTemp / 255.0, w=w) * 255
  File "E:\BaiduNetdiskWorkspace\Cloud_PythonProgramming\img-proc-app\plugins\defogger.py", line 60, in defogging
    V1, A = getV1(m, r, eps, w, maxV1)  # 得到遮罩图像和大气光照
  File "E:\BaiduNetdiskWorkspace\Cloud_PythonProgramming\img-proc-app\plugins\defogger.py", line 43, in getV1
    V1 = min(m, 2)  # 得到暗通道图像
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

